# Generated by Django 3.1.7 on 2022-12-01 14:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20221201_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='city',
            field=models.CharField(choices=[], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 1, 19, 50, 21, 677733)),
        ),
    ]
