# Generated by Django 3.1.7 on 2022-12-10 10:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20221202_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='city',
            field=models.CharField(choices=[('1', 'birmingham'), ('2', '\tbolton'), ('3', 'leeds'), ('4', 'manchester'), ('5', 'liverpool'), ('6', 'london'), ('7', 'sheffield'), ('8', 'bradford')], max_length=20),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 10, 16, 22, 12, 308702)),
        ),
        migrations.CreateModel(
            name='UserFavProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(default=False)),
                ('property', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.properties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
