# Generated by Django 3.1.7 on 2022-12-12 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20221210_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadableAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='media/download_assets')),
                ('desc', models.TextField(blank=True, default=' ')),
                ('downloadable_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 12, 9, 20, 56, 873537)),
        ),
    ]
