# Generated by Django 3.1.7 on 2022-12-12 04:45

import datetime
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20221212_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadableassets',
            name='img',
            field=models.FileField(default='', upload_to='media/download_assets'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='downloadableassets',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[300, 180], upload_to='media/download_assets'),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 12, 10, 15, 8, 837549)),
        ),
    ]
