# Generated by Django 3.1.7 on 2022-12-12 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20221212_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadableassets',
            name='img',
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 12, 10, 24, 4, 372502)),
        ),
    ]
