# Generated by Django 3.1.7 on 2022-12-14 06:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20221213_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='is_exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='properties',
            name='is_underconstruction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='constructionupdates',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 14, 12, 22, 48, 544247)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 14, 12, 22, 48, 525611)),
        ),
        migrations.CreateModel(
            name='UserExclusiveProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.properties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
