# Generated by Django 3.1.7 on 2022-12-28 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20221228_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionupdates',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 28, 17, 27, 38, 282837)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 28, 17, 27, 38, 269847)),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
