# Generated by Django 3.1.7 on 2022-12-28 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20221228_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='image',
            field=models.FileField(default='default.png', upload_to='media/team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='constructionupdates',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 28, 17, 42, 21, 823320)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 28, 17, 42, 21, 811770)),
        ),
    ]
