# Generated by Django 3.1.7 on 2023-01-02 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20221228_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionupdates',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 2, 13, 20, 16, 869664)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 2, 13, 20, 16, 841173)),
        ),
    ]
