# Generated by Django 3.1.7 on 2023-01-03 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20230103_1052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityGuide',
        ),
        migrations.AddField(
            model_name='teammembers',
            name='card_1_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='card_1_image',
            field=models.FileField(blank=True, upload_to='media/guide/city/c1'),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='card_1_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='card_2_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='card_2_image',
            field=models.FileField(blank=True, upload_to='media/guide/city/c2'),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='card_2_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='card_3_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='card_3_image',
            field=models.FileField(blank=True, upload_to='media/guide/city/c3'),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='card_3_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='q_1_desc',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='q_1_image',
            field=models.FileField(blank=True, default='default.png', upload_to='media/guide/city/q1'),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='q_1_title',
            field=models.CharField(blank=True, default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='q_2_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='q_2_image',
            field=models.FileField(blank=True, upload_to='media/guide/city/q2'),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='q_2_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='q_3_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='q_3_image',
            field=models.FileField(blank=True, upload_to='media/guide/city/q3'),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='q_3_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='constructionupdates',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 10, 55, 34, 620339)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 10, 55, 34, 557442)),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='image',
            field=models.FileField(upload_to='media/guide/city'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
