# Generated by Django 3.1.7 on 2023-01-03 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_auto_20230103_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='card_1_desc',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='card_1_image',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='card_1_title',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='card_2_desc',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='card_2_image',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='card_2_title',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='card_3_desc',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='card_3_image',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='card_3_title',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='q_1_desc',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='q_1_image',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='q_1_title',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='q_2_desc',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='q_2_image',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='q_2_title',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='q_3_desc',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='q_3_image',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='q_3_title',
        ),
        migrations.AlterField(
            model_name='constructionupdates',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 10, 56, 19, 233764)),
        ),
        migrations.AlterField(
            model_name='properties',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 10, 56, 19, 181386)),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='image',
            field=models.FileField(upload_to='media/team'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
